eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

server:
  port: 8888
  
spring:
  application:
    name: assessment-config-server-ms
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmadtausif38/Assessment-ConfigServer
          clone-on-start: true
          default-label: main
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_CONFIG_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"
