spring:
  config:
    import: optional:configserver:http://localhost:8888  # URL of the Config Server
    fail-fast: true  # Optional: fail startup if the config server is not available
    retry:
      max-attempts: 6  # Optional: number of retry attempts if config server is unreachable
      initial-interval: 2000  # Time between retries (in ms)

  cloud:
    config:
      name: assessment-authentication-ms
