server:
  port: 0

spring:
  application:
    name: assessment-admin-ms
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
  config:
    import: optional:configserver:http://localhost:8888  # Config server URL


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    